### ISSUE TITLE
ImportError: No module named 'Users'

### ISSUE THREAD

**Issue by tekumara** [quora/pyanalyze#14]
```
$  python -m pyanalyze tests
Traceback (most recent call last):
  File "/Users/tekumara/.virtualenvs/brp/lib/python3.6/site-packages/pyanalyze/name_check_visitor.py", line 632, in _load_module
    return self.load_module(self.filename)
  File "/Users/tekumara/.virtualenvs/brp/lib/python3.6/site-packages/pyanalyze/name_check_visitor.py", line 653, in load_module
    filename, self.config.PATHS_EXCLUDED_FROM_IMPORT
  File "/Users/tekumara/.virtualenvs/brp/lib/python3.6/site-packages/pyanalyze/importer.py", line 56, in load_module_from_file
    module = _importer.importFromPath(abspath, module_path)
  File "/Users/tekumara/.virtualenvs/brp/lib/python3.6/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/Users/tekumara/.virtualenvs/brp/lib/python3.6/site-packages/nose/importer.py", line 79, in importFromDir
    fh, filename, desc = find_module(part, path)
  File "/Users/tekumara/.pyenv/versions/3.6.10/lib/python3.6/imp.py", line 297, in find_module
    raise ImportError(_ERR_MSG.format(name), name=name)
ImportError: No module named 'Users'
```

**Comment by JelleZijlstra** [comment]
Looks like the code you're looking at isn't directly importable. Does `PYTHONPATH=. python -m pyanalyze tests` work?

**Comment by tekumara** [comment]
Ah thank you that worked! (no errors, or output this time)

**Comment by tekumara** [comment]
FYI: `pip install -e .` first also fixed this.
