### ISSUE TITLE
Pyanalyze errors out with a raw traceback when running without a path argument (`pyanalyze`), instead of behaving as `pyanalyze .` or printing usage

### ISSUE THREAD

**Issue by CAM-Gerlach** [quora/pyanalyze#219]
Simply running `pyanalyze` in an empty (or full, or any) directory results in a raw traceback being printed, rather than printing usage or a helpful error, whereas `pyanalyze .` works as expected. Given the latter, it would make sense to simply assume `.` if no path was passed, like flake8 does , or at the very least, like `mypy` does, have your CLI parser handle it and output the appropriate message.

Error message:

<details>

```python-traceback
Traceback (most recent call last):
  File "C:\Miniconda3\envs\praw-env\Scripts\pyanalyze-script.py", line 33, in <module>
    sys.exit(load_entry_point('pyanalyze', 'console_scripts', 'pyanalyze')())
  File "c:\users\c. a. m. gerlach\documents\dev\spacex\pyanalyze\pyanalyze\__main__.py", line 5, in main
    NameCheckVisitor.main()
  File "c:\users\c. a. m. gerlach\documents\dev\spacex\pyanalyze\pyanalyze\node_visitor.py", line 385, in main
    failures = cls._run(**kwargs)
  File "c:\users\c. a. m. gerlach\documents\dev\spacex\pyanalyze\pyanalyze\node_visitor.py", line 673, in _run
    result = cls._run_on_files_or_all(**kwargs)
  File "c:\users\c. a. m. gerlach\documents\dev\spacex\pyanalyze\pyanalyze\node_visitor.py", line 682, in _run_on_files_or_all
    return cls.check_all_files(**kwargs)
  File "c:\users\c. a. m. gerlach\documents\dev\spacex\pyanalyze\pyanalyze\name_check_visitor.py", line 4217, in check_all_files
    return super().check_all_files(*args, **kwargs)
  File "c:\users\c. a. m. gerlach\documents\dev\spacex\pyanalyze\pyanalyze\node_visitor.py", line 303, in check_all_files
    files = cls.get_files_to_check(include_tests)
  File "c:\users\c. a. m. gerlach\documents\dev\spacex\pyanalyze\pyanalyze\node_visitor.py", line 326, in get_files_to_check
    return sorted(set(cls._get_all_python_files(include_tests=include_tests)))
  File "c:\users\c. a. m. gerlach\documents\dev\spacex\pyanalyze\pyanalyze\node_visitor.py", line 904, in _get_all_python_files
    enclosing_module_names = {module.__name__ for module in modules}
  File "c:\users\c. a. m. gerlach\documents\dev\spacex\pyanalyze\pyanalyze\node_visitor.py", line 904, in <setcomp>
    enclosing_module_names = {module.__name__ for module in modules}
AttributeError: 'NoneType' object has no attribute '__name__'
```

</details>

**Comment by JelleZijlstra** [comment]
Oops, good catch. I think defaulting to `.` makes sense.
