### ISSUE TITLE
ImportError on running current version of pyanalyze inside container

### ISSUE THREAD

**Issue by BenQuigley** [quora/pyanalyze#581]
In a Debian 10 docker container on my MacOS 12.1 arm64 machine, installing the current version of pyanalyze and running it on any python file, or with no arguments, outputs this error:

```
# pyanalyze
Traceback (most recent call last):
  File "/usr/local/bin/pyanalyze", line 5, in <module>
    from pyanalyze.__main__ import main
  File "/usr/local/lib/python3.9/site-packages/pyanalyze/__init__.py", line 9, in <module>
    from . import (
  File "/usr/local/lib/python3.9/site-packages/pyanalyze/annotations.py", line 66, in <module>
    from .functions import FunctionDefNode
  File "/usr/local/lib/python3.9/site-packages/pyanalyze/functions.py", line 24, in <module>
    from .signature import ParameterKind, Signature, SigParameter
  File "/usr/local/lib/python3.9/site-packages/pyanalyze/signature.py", line 37, in <module>
    from typing_extensions import assert_never, Literal, Protocol, Self
ImportError: cannot import name 'assert_never' from 'typing_extensions' (/usr/local/lib/python3.9/site-packages/typing_extensions.py)
```

My pyanalyze version is 0.8.0 (the current release version) and this is Python 3.9.9.

Installing pyanalyze on the host Mac does not have this issue (but then I can't analyze my code, which is installed in the container).

**Comment by JelleZijlstra** [comment]
Seems like the typing-extensions dependency is incorrect; we request 4.0.0 but assert_never() was added in 4.1.0. I believe #582 should fix. Until there is a release, you can work around this by explicitly requesting `typing_extensions>=4.1.0` when you install pyanalyze in your container.

**Comment by BenQuigley** [comment]
Thank you!
